{{- range .Values.argocd }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
            namespace: {{ .namespace }}
  template:
    metadata:
      name: {{ .name | quote }}
    spec:
      project: default
      source:
        repoURL: {{ .repoURL | quote }}
        targetRevision: {{ .targetRevision | quote }}
        path: {{ .path | quote }}
        {{- with .helm }}
        helm:
          {{- toYaml . | nindent 10}}
        {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ .namespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
---
{{- end }}